### ISSUE TITLE
Backoffs and 429s on /keys/claim over federation causes UTDs

### ISSUE THREAD

**Issue by kegsay** [element-hq/synapse#17267] opened 2024-06-05 13:14 UTC
### Description

Debugging a UTD ([rageshake](https://github.com/matrix-org/element-ios-rageshakes/issues/29829)) and the cause of this appears to be `/keys/claim` failing with:
```
failures={"connecteu.rs": Object {"message": String("Not ready for retry"), "status": Number(503)}, "sw1v.org": Object {"message": String("Not ready for retry"), "status": Number(503)}}
```

This happens again 40 minutes later, which feels very wrong if the retry period is 40mins+.

A long retry period like this will cause UTDs because the sender cannot claim the OTK for one or more of the device's recipients.

The error message originates [here](https://github.com/element-hq/synapse/blob/fcbc79bb87d08147e86dafa0fee5a9aec4d3fc23/synapse/handlers/e2e_keys.py#L1614) which is called from [here](https://github.com/element-hq/synapse/blob/fcbc79bb87d08147e86dafa0fee5a9aec4d3fc23/synapse/handlers/e2e_keys.py#L743) for claiming keys. This calls through to the [transport layer](https://github.com/element-hq/synapse/blob/fcbc79bb87d08147e86dafa0fee5a9aec4d3fc23/synapse/federation/federation_client.py#L311) which does [post_json](https://github.com/element-hq/synapse/blob/fcbc79bb87d08147e86dafa0fee5a9aec4d3fc23/synapse/federation/transport/client.py#L678) which shows it can throw [NotRetryingDestination](https://github.com/element-hq/synapse/blob/fcbc79bb87d08147e86dafa0fee5a9aec4d3fc23/synapse/http/matrixfederationclient.py#L583).

It seems to be thrown in [get_retry_limiter](https://github.com/element-hq/synapse/blob/fcbc79bb87d08147e86dafa0fee5a9aec4d3fc23/synapse/http/matrixfederationclient.py#L610) [here](https://github.com/element-hq/synapse/blob/fcbc79bb87d08147e86dafa0fee5a9aec4d3fc23/synapse/util/retryutils.py#L105). The retry interval controls the duration, which seems to be [persisted](https://github.com/element-hq/synapse/blob/fcbc79bb87d08147e86dafa0fee5a9aec4d3fc23/synapse/storage/databases/main/transactions.py#L198). This is loaded [here](https://github.com/element-hq/synapse/blob/fcbc79bb87d08147e86dafa0fee5a9aec4d3fc23/synapse/util/retryutils.py#L158) and is modified according to:
```py
                self.retry_interval = int(
                    self.retry_interval
                    * self.destination_retry_multiplier
                    * random.uniform(0.8, 1.4)
                )
```

The retry multiplier is a [configurable value](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#federation-1) and retry interval defaults to the min: `self.retry_interval = self.destination_min_retry_interval_ms`. So what's matrix.org's config?

### Steps to reproduce

I'm guessing:
 - make your server go offline for a bit
 - come back online
 - have it not retry for ages?

### Homeserver

matrix.org

### Synapse Version

Whatever was running on May 30

### Installation Method

I don't know

### Database

postgres

### Workers

Multiple workers

### Platform

?

### Relevant log output

```shell
client-side:

`2024-05-30 09:29:57.003 Element[7064:2329509] [MXCryptoSDK] DEBUG receive_keys_claim_response ... failures={"connecteu.rs": Object {"message": String("Not ready for retry"), "status": Number(503)}, "sw1v.org": Object {"message": String("Not ready for retry"), "status": Number(503)}}`
```

### Anything else that would be useful to know?

Proposed solution here would be to ignore the backoff for `/keys/claim` requests, as if they fail it will definitely cause a UTD. If we don't want to do that, having a suitably low retry period (capped in the order of minutes) could be a viable alternative.

Alternatively, I had assumed that Synapse cleared backoffs when the other HS sent something to matrix.org..? Surely this would have happened here?

**Comment by richvdh** [comment] 2024-06-05 14:21
I think this is a duplicate of https://github.com/element-hq/synapse/issues/8917

**Comment by richvdh** [comment] 2024-06-06 13:36
Also: it might be better described as "backoff period" than "retry period", since synapse doesn't itself initiate any retries for `/keys/claim` ?

**Comment by kegsay** [comment] 2024-06-07 08:34
I've seen this happen again but this time between element.io <--> matrix.org, where the client on element.io saw in response to /keys/claim: `"matrix.org": Object {"message": String("Failed to send request: HttpResponseException: 429: Too Many Requests"), "status": Number(503.0)}`

Rate limiting this endpoint feels suboptimal...

**Comment by kegsay** [comment] 2024-06-07 10:56
https://github.com/matrix-org/matrix-spec-proposals/pull/4081 would be a solution to this because then the sending server could just serve up the fallback key.

**Comment by ara4n** [comment] 2024-06-07 17:52
@kegsay pretty sure this isn't a 429 but really a 503 (see the `status` field), which matrix.org's haproxy turns into a 429 because if a single endpoint reports 503 to CF then CF will mark the whole haproxy as down, taking out the whole service. It's a horrible hack, given it's absolutely nothing to do with rate limiting; i suspect 429 was chosen as a code which would encourage retries without the backend being marked as down.

**Comment by andybalaam** [comment] 2024-06-10 13:53
Crypto are not actively working on this because the best solution would be to do https://github.com/matrix-org/matrix-spec-proposals/pull/4081

**Comment by kegsay** [comment] 2024-07-11 15:20
Another one, element.io <-> matrix.org failing with a different error: `failures={"matrix.org": Object {"status": Number(503), "message": String("Failed to send request: TimeoutError: Timed out after 10s")}}`

**Comment by kegsay** [comment] 2024-07-12 09:12
This happened again in a large E2EE room. The failure mode was subtly different though because `/keys/claim` did eventually succeed for a 2nd+ message, so the error message was `The message was encrypted using an unknown message index, first known index 1, index of the message 0` rather than not having the keys at all.

**Comment by richvdh** [comment] 2024-10-17 14:14
It's unclear to me how this is different from https://github.com/element-hq/element-meta/issues/2154, which covers the implementation of MSC4081.

Closing for now, unless someone can clarify

**Closed by richvdh** 2024-10-17 14:14 UTC
Labels: A-E2EE, O-Occasional, T-Defect, z-uisi
