### ISSUE TITLE
ValueError: 2130706432 is not a valid 128-bit unsigned integer! when Python does not have IPv6 support enabled

### ISSUE THREAD

**Issue by jSML4ThWwBID69YC** [element-hq/synapse#16996] opened 2024-03-16 01:25 UTC
### Description

I had a working Synapse v1.98. I attempted to upgrade it to the latest release. The following error occurs on restart of the synctl binary. 

```
# ./bin/synctl start
Traceback (most recent call last):
  File "/home/synapse/lib/python3.11/site-packages/netaddr/strategy/ipv6.py", line 170, in int_to_str
    addr = _inet_ntop(AF_INET6, packed_int)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/synapse/lib/python3.11/site-packages/netaddr/fbsocket.py", line 98, in inet_ntop
    ipv4_str = inet_ntoa(packed_ipv4)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/synapse/lib/python3.11/site-packages/netaddr/fbsocket.py", line 20, in inet_ntoa
    raise TypeError('string type expected, not %s' % type(packed_ip))
TypeError: string type expected, not <class 'bytes'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/synapse/lib/python3.11/site-packages/synapse/app/homeserver.py", line 404, in <module>
    main()
  File "/home/synapse/lib/python3.11/site-packages/synapse/app/homeserver.py", line 394, in main
    hs = setup(sys.argv[1:])
         ^^^^^^^^^^^^^^^^^^^
  File "/home/synapse/lib/python3.11/site-packages/synapse/app/homeserver.py", line 303, in setup
    config = HomeServerConfig.load_or_generate_config(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/synapse/lib/python3.11/site-packages/synapse/config/_base.py", line 806, in load_or_generate_config
    obj.parse_config_dict(
  File "/home/synapse/lib/python3.11/site-packages/synapse/config/_base.py", line 827, in parse_config_dict
    self.invoke_all(
  File "/home/synapse/lib/python3.11/site-packages/synapse/config/_base.py", line 426, in invoke_all
    res[config_class.section] = getattr(config, func_name)(*args, **kwargs)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/synapse/lib/python3.11/site-packages/synapse/config/server.py", line 533, in read_config
    self.ip_range_blocklist = generate_ip_set(
                              ^^^^^^^^^^^^^^^^
  File "/home/synapse/lib/python3.11/site-packages/synapse/config/server.py", line 116, in generate_ip_set
    result.add(IPNetwork(network).ipv6(ipv4_compatible=True))
  File "/home/synapse/lib/python3.11/site-packages/netaddr/ip/sets.py", line 289, in add
    self._compact_single_network(addr)
  File "/home/synapse/lib/python3.11/site-packages/netaddr/ip/sets.py", line 190, in _compact_single_network
    candidate = added_network.previous()
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/synapse/lib/python3.11/site-packages/netaddr/ip/__init__.py", line 1304, in previous
    ip_copy = self.__class__('%s/%d' % (self.network, self.prefixlen), self._module.version)
                             ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  File "/home/synapse/lib/python3.11/site-packages/netaddr/ip/__init__.py", line 676, in __str__
    return self._module.int_to_str(self._value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/synapse/lib/python3.11/site-packages/netaddr/strategy/ipv6.py", line 177, in int_to_str
    raise ValueError('%r is not a valid 128-bit unsigned integer!' % (int_val,))
ValueError: 2130706432 is not a valid 128-bit unsigned integer!
synapse.app.homeserver(homeserver.yaml) failed to start (exit code: 1). Check the Synapse logfile, or run synctl with --no-daemonize.

```

For sake of testing, I did a fresh installation and see the same error. There is nothing in the logs, and running it with --no-daemonize leads to the same error. 

### Steps to reproduce

Here are my testing steps using a new installation. The server has Python 3.11 installed on it already. Note, python does not have IPv6 support built in.

```
python3.11 -m venv /home/synapse
cd /home/synapse
source /home/synapse/bin/activate
pip install "matrix-synapse[postgres]"
python -m synapse.app.homeserver --server-name example.com --config-path homeserver.yaml --generate-config --report-stats=no
./bin/synctl start
```

### Homeserver

private

### Synapse Version

1.98 to 1.99 or a clean installation of 1.102.0

### Installation Method

pip (from PyPI)

### Database

Postgres and sqlite depending on test

### Workers

Single process

### Platform

OS: FreeBSD
Python 3.11 is installed. Synapse is done in a venv. 

### Configuration

The old installation uses unix sockets. The new installation has no configuration done at the time of the error. 

### Relevant log output

```shell
# ./bin/synctl start
Traceback (most recent call last):
  File "/home/synapse/lib/python3.11/site-packages/netaddr/strategy/ipv6.py", line 170, in int_to_str
    addr = _inet_ntop(AF_INET6, packed_int)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/synapse/lib/python3.11/site-packages/netaddr/fbsocket.py", line 98, in inet_ntop
    ipv4_str = inet_ntoa(packed_ipv4)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/synapse/lib/python3.11/site-packages/netaddr/fbsocket.py", line 20, in inet_ntoa
    raise TypeError('string type expected, not %s' % type(packed_ip))
TypeError: string type expected, not <class 'bytes'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/synapse/lib/python3.11/site-packages/synapse/app/homeserver.py", line 404, in <module>
    main()
  File "/home/synapse/lib/python3.11/site-packages/synapse/app/homeserver.py", line 394, in main
    hs = setup(sys.argv[1:])
         ^^^^^^^^^^^^^^^^^^^
  File "/home/synapse/lib/python3.11/site-packages/synapse/app/homeserver.py", line 303, in setup
    config = HomeServerConfig.load_or_generate_config(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/synapse/lib/python3.11/site-packages/synapse/config/_base.py", line 806, in load_or_generate_config
    obj.parse_config_dict(
  File "/home/synapse/lib/python3.11/site-packages/synapse/config/_base.py", line 827, in parse_config_dict
    self.invoke_all(
  File "/home/synapse/lib/python3.11/site-packages/synapse/config/_base.py", line 426, in invoke_all
    res[config_class.section] = getattr(config, func_name)(*args, **kwargs)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/synapse/lib/python3.11/site-packages/synapse/config/server.py", line 533, in read_config
    self.ip_range_blocklist = generate_ip_set(
                              ^^^^^^^^^^^^^^^^
  File "/home/synapse/lib/python3.11/site-packages/synapse/config/server.py", line 116, in generate_ip_set
    result.add(IPNetwork(network).ipv6(ipv4_compatible=True))
  File "/home/synapse/lib/python3.11/site-packages/netaddr/ip/sets.py", line 289, in add
    self._compact_single_network(addr)
  File "/home/synapse/lib/python3.11/site-packages/netaddr/ip/sets.py", line 190, in _compact_single_network
    candidate = added_network.previous()
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/synapse/lib/python3.11/site-packages/netaddr/ip/__init__.py", line 1304, in previous
    ip_copy = self.__class__('%s/%d' % (self.network, self.prefixlen), self._module.version)
                             ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  File "/home/synapse/lib/python3.11/site-packages/netaddr/ip/__init__.py", line 676, in __str__
    return self._module.int_to_str(self._value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/synapse/lib/python3.11/site-packages/netaddr/strategy/ipv6.py", line 177, in int_to_str
    raise ValueError('%r is not a valid 128-bit unsigned integer!' % (int_val,))
ValueError: 2130706432 is not a valid 128-bit unsigned integer!
synapse.app.homeserver(homeserver.yaml) failed to start (exit code: 1). Check the Synapse logfile, or run synctl with --no-daemonize.
```

### Anything else that would be useful to know?

Python was built without IPv6 support. The first test uses an older version of Synapse that has been running for several years. The second test used the latest release. The same error happens either way.

**Comment by jSML4ThWwBID69YC** [comment] 2024-03-16 20:56
This was resolved by rebuilding python with IPv6 support. This works even if there is no IPv6 address assigned.

**Comment by andrewhotlab** [comment] 2024-05-08 09:09
Thank you. I just hit the same issue upgrading `py-netaddr` from v0.10.1 to v1.2.1 as posted [here](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=277810#c5).
I'm not able to diagnose is, but maybe it might be related to netaddr/netaddr#381?

Just solved recompiling Python with IPv6 support too (even if it is not enabled at OS level).

**Comment by reivilibre** [comment] 2024-05-09 12:46
Hi folks,

Appreciate this does technically count as a bug, but given the niche circumstances (unusual configuration when compiling Python) and the relative ease of a workaround (enabling IPv6, which is commonly done), I don't think it makes much sense for us to dig into this.

We might take a PR, but I also suspect that the motivation is not going to be there for anyone to seriously care enough to fix this (?).

So on that note I will close this, but thanks for reporting and I hope this issue will still be found by people so they can find the cause.

**Closed by reivilibre** 2024-05-09 12:46 UTC
