### ISSUE TITLE
Timeout in updating v3/profile/<mxid>/displayname on large account

### ISSUE THREAD

**Issue by neilisfragile** [element-hq/synapse#17052] opened 2024-04-04 21:30 UTC
### Description

I am trying to update my display name, my client (Element Web in this case) reports an error following the HTTP request timing out. However the display name update goes through as intended. 

### Steps to reproduce

Make a PUT request to v3/profile/<mxid>/displayname of a large account (600-700 rooms) - wait for a timeout. 

### Homeserver

matrix.org

### Synapse Version

"Synapse","version":"1.103.0 (b=matrix-org-hotfixes,7d5f3ea750,dirty)"

### Installation Method

Docker (matrixdotorg/synapse)

### Database

matrix.org

### Workers

Multiple workers

### Platform

matrix.org

### Configuration

matrix.org

### Relevant log output

```shell
matrix.org
```

### Anything else that would be useful to know?

I cannot reproduce this on a small account. My account has about 600-700 rooms, and I assume the timeout is caused by updating the state in each room. 

I don't believe this to be a new bug.

**Comment by dklimpel** [comment] 2024-04-05 05:47
Related to:
- #1297

**Comment by richvdh** [comment] 2024-11-27 09:57
Duplicate of https://github.com/element-hq/synapse/issues/1297

**Closed by richvdh** 2024-11-27 09:57 UTC
