### ISSUE TITLE
Allow Configurable Server-Default Push Rules for Notifications

### ISSUE THREAD

**Issue by bartvdbraak** [element-hq/synapse#17405] opened 2024-07-08 08:42 UTC
**Description:**

Currently, the server-default push rules are hard-coded, making it difficult to change these defaults without modifying the source code.

**Issue:**

We want new users, who haven't set any overrides on the user or room level for push rules, to have specific default notification settings. Specifically, we want the default notification setting to be "Mention only."

**Context:**

- **Current Limitation:** There is no straightforward way to override these defaults through configuration. As confirmed by community members in the Matrix support room, this requires altering the source code.
- **Reference:** The relevant code can be found here: [Base Rules Source Code](https://github.com/element-hq/synapse/blob/develop/rust/src/push/base_rules.rs#L292).
- **Documentation:** According to the [Predefined Rules Documentation](https://spec.matrix.org/latest/client-server-api/#predefined-rules) it seems that these defaults should be configurable.

**Comment by clokep** [comment] 2024-07-10 00:55
Duplicate of #9325, I think.

**Comment by sandhose** [comment] 2024-07-15 07:43
This indeed looks duplicate. @bartvdbraak could you add the same details (links to the source and spec doc) to the other issue? I'm closing this one

Duplicate of #9325

**Closed by sandhose** 2024-07-15 07:43 UTC
