### ISSUE TITLE
After changing the profile picture, all unread group chats disappear

### ISSUE THREAD

**Issue by yangjl114** [element-hq/synapse#17603] opened 2024-08-23 02:29 UTC
### Description

After element-web changes the profile picture, the event is sent in each group chat, 
causing the unread messages to be cleared. 
How can this event not affect the unread statistics of messages

### Steps to reproduce

1. Modify the profile picture
2. Each group chat sent the event
3. Unread statistics in group chats disappear

### Homeserver

https://tjfydi.com:5443

### Synapse Version

server_version:1.106.0

### Installation Method

Docker (matrixdotorg/synapse)

### Database

single / no / no

### Workers

Single process

### Platform

cent os 7.8
docker 26.1.2

### Relevant log output

```shell
.
```

**Comment by anoadragon453** [comment] 2024-08-29 14:22
Duplicate of https://github.com/element-hq/synapse/issues/16373 (and yes, it's quite annoying).

It's a result of needing to send a new join event in every room you're in, such that you can update your per-room avatar.

**Closed by anoadragon453** 2024-08-29 14:22 UTC
